[package]
name = "secret"
version = "0.1.0"
edition = "2021"

[dependencies]

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
direct-export = "interface"

[package.metadata.component.exports]
interface = "../../wit/trinity-module.wit"
