[package]
name = "uuid"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = "1.2.1"
wit-sys.workspace = true
libcommand.workspace = true

[lib]
crate-type = ["cdylib"]

[package.metadata.component]
target.path = "../../wit/trinity-module.wit"
