name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    env:
        RUST_BACKTRACE: 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: clippy, rustfmt

      - uses: Swatinem/rust-cache@v1

      - name: Format host
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all -- --check

      - name: Check host
        uses: actions-rs/cargo@v1
        with:
          command: check
          args: --all --verbose

  ci-modules:
    env:
        RUST_BACKTRACE: 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly

    steps:
      - uses: actions/checkout@v2

      - uses: Swatinem/rust-cache@v1

      - name: Format modules
        uses: actions-rs/cargo@v1
        with:
          command: fmt
          args: --all --manifest-path ./modules/Cargo.toml -- --check

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cargo-component
        working-directory: ./modules/
        run: |
          rustup update
          cargo component --version || ./install-cargo-component.sh

      - name: Check modules
        working-directory: ./modules/
        run: cargo component check
