name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  ci:
    env:
        RUST_BACKTRACE: 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          override: true
          components: rustfmt

      - name: Load cache
        uses: Swatinem/rust-cache@v2

      - name: Format host
        run: |
          cargo fmt --all -- --check

      - name: Check host
        run: |
          cargo check --all --verbose

  ci-modules:
    env:
        RUST_BACKTRACE: 1
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable
          - nightly

    steps:
      - uses: actions/checkout@v3

      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          toolchain: ${{ matrix.rust }}
          targets: wasm32-unknown-unknown
          components: rustfmt

      - uses: Swatinem/rust-cache@v2

      - name: Format modules
        run: |
          cargo fmt --all --manifest-path ./modules/Cargo.toml -- --check

      - name: Install Protoc
        uses: arduino/setup-protoc@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Install cargo-component
        working-directory: ./modules/
        run: |
          wget https://github.com/bytecodealliance/cargo-component/releases/download/v0.4.0/cargo-component-x86_64-unknown-linux-gnu
          chmod +x ./cargo-component-x86_64-unknown-linux-gnu
          mv ./cargo-component-x86_64-unknown-linux-gnu ~/.cargo/bin/cargo-component

      - name: Check modules
        working-directory: ./modules/
        run: cargo component check
